- name: install packages
  apt:
    pkg={{ item }}
    state=latest
  when: (ansible_os_family == "Debian")
  with_items: vsftpd.packages
  tags:
    - ftp

- name: install packages
  yum:
    pkg={{ item }}
    state=latest
  when: (ansible_os_family == "RedHat")
  with_items: vsftpd.packages
  tags:
    - ftp