- name: set permission
  file:
    path={{ stores_dir }}
    state=directory
    mode=555
    owner={{ deploy.user }}
    group={{ deploy.group }}
  tags:
    - common
    - deploy

- name: create project directories
  file:
    path={{ stores_dir }}/{{ item.key }}
    state=directory
    mode=755
    owner=root
    group=root
  ignore_errors: true
  with_dict: stores
  tags:
    - nginx
    - php
    - deploy