- name: enable autoload after boot
  service:
    name={{ postfix_role.service }}
    enabled=yes
  tags:
    - mail

- name: restart
  service:
    name={{ postfix_role.service }}
    state=restarted
  tags:
    - mail