---

- name: installing packages
  yum:
    name={{ item }}
    state=latest
  with_items: logrotate_role.packages
  when: (ansible_os_family == "RedHat")
  tags:
    - logrotate

- name: installing packages
  apt:
    name={{ item }}
    state=latest
    update_cache=yes
  with_items: logrotate_role.packages
  when: (ansible_os_family == "Debian")
  tags:
    - logrotate