- name: put into autostart
  service:
    name={{ fail2ban_role.service }}
    enabled=yes
  tags:
    - firewall

- name: restart
  service:
    name={{ fail2ban_role.service }}
    state=restarted
  ignore_errors: True
  tags:
    - firewall