- name: checking for previous installation
  stat: path=/usr/sbin/mysqld
  register: mysqld_stat

- name: preseeding MySQL file
  template: src=preseed.j2 dest=/root/mysql.seed
  when: (ansible_os_family == "Debian") and (mysqld_stat.stat.exists == False)

- command: /usr/bin/debconf-set-selections /root/mysql.seed
  when: (ansible_os_family == "Debian") and (mysqld_stat.stat.exists == False)
